from sqlalchemy import create_engine, Column, Integer, Text, Float, ForeignKey, JSON, Enum, DateTime, String, CheckConstraint
from sqlalchemy.dialects.postgresql import ENUM
# from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import text, select, desc, asc
from sqlalchemy.types import UserDefinedType
from sqlalchemy.sql import func
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import UUID, JSONB

import uuid
from typing import Union, Dict, Any, List, Tuple

import datetime
import enum

try:
    import config
    import utils
except ImportError:
    from src import config
    from src import utils

logger = utils.custom_logger(__name__)

DATABASE_URL = config.PG_CONNECTION_STRING

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

jobstatus_enum = ENUM('queued', 'scheduled', 'in-progress', 'completed', 'failed', name='jobstatus_enum', create_type=False)
docstatus_enum = ENUM('active', 'inactive', name='docstatus_enum', create_type=False)
language_enum = ENUM('en', 'es', 'fr', name='language_enum', create_type=False)


class Queries(enum.Enum):
    CREATE_EXTENSION = "CREATE EXTENSION IF NOT EXISTS vector;"
    
    CREATE_TYPE_ENUM_DOCSTATUS = """
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'docstatus_enum') THEN
            CREATE TYPE docstatus_enum AS ENUM ('active', 'inactive');
        END IF;
    END
    $$;
    """

    CREATE_TYPE_ENUM_JOBSTATUS = """
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'jobstatus_enum') THEN
            CREATE TYPE jobstatus_enum AS ENUM ('queued', 'scheduled', 'in-progress', 'completed', 'failed');
        END IF;
    END
    $$;
    """

    CREATE_TYPE_ENUM_LANGUAGE = """
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'language_enum') THEN
            CREATE TYPE language_enum AS ENUM ('en', 'es', 'fr');
        END IF;
    END
    $$;
    """

    CREATE_TABLE_DOCUMENT = f"""CREATE TABLE IF NOT EXISTS document (
        _id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        collection_id BIGINT NOT NULL,
        s3_path VARCHAR(1024) NOT NULL,
        text TEXT NOT NULL,
        embedding VECTOR({config.VECTOR_SIZE}) NOT NULL,
        tags JSON,
        status docstatus_enum DEFAULT 'active',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );"""

    CREATE_TABLE_COLLECTION = """CREATE TABLE IF NOT EXISTS collection (
        _id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tenant_id VARCHAR(256) NOT NULL,
        name VARCHAR(64) NOT NULL UNIQUE,
        description TEXT,
        language language_enum DEFAULT 'en',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );"""


    CREATE_TABLE_JOB = """CREATE TABLE IF NOT EXISTS job (
        _id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        id VARCHAR(64) UNIQUE,
        type VARCHAR(64) NOT NULL,
        meta JSON,
        status jobstatus_enum DEFAULT 'scheduled',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );"""

class Document(Base):
    __tablename__ = 'document'

    _id = Column(Integer, primary_key=True, index=True)
    collection_id = Column(Integer, index=True)
    s3_path = Column(String(1024), nullable=False)
    text = Column(Text, nullable=False)
    embedding = Column(Vector(config.VECTOR_SIZE), nullable=False)
    tags = Column(JSON)
    status = Column('status', docstatus_enum, default='active')
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.datetime.utcnow, default=datetime.datetime.utcnow)


class Collection(Base):
    __tablename__ = 'collection'

    _id = Column(Integer, primary_key=True, index=True)
    tenant_id = Column(String(256), nullable=False)
    name = Column(String(64), nullable=False, unique=True)
    description = Column(Text)
    language = Column('language', language_enum, default='en')
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.datetime.utcnow, default=datetime.datetime.utcnow)

class Job(Base):
    __tablename__ = 'job'

    _id = Column(Integer, primary_key=True, index=True)
    id = Column(String(64), unique=True)
    type = Column(String(64), nullable=False)
    meta = Column(JSON)
    status = Column('status', jobstatus_enum, default='scheduled')
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.datetime.utcnow, default=datetime.datetime.utcnow)


# class Vector(UserDefinedType):
#     def get_col_spec(self):
#         return "vector"

def init_db():
    with engine.connect() as connection:
        connection.execute(text(Queries.CREATE_TYPE_ENUM_JOBSTATUS.value))
        connection.execute(text(Queries.CREATE_TYPE_ENUM_DOCSTATUS.value))
        connection.execute(text(Queries.CREATE_TYPE_ENUM_LANGUAGE.value))
        connection.execute(text(Queries.CREATE_EXTENSION.value))
        connection.execute(text(Queries.CREATE_TABLE_DOCUMENT.value))
        connection.execute(text(Queries.CREATE_TABLE_COLLECTION.value))
        connection.execute(text(Queries.CREATE_TABLE_JOB.value))
        connection.commit()

    # Base.metadata.create_all(bind=engine)


def update_job_status(job_id: str, status: str) -> Job:
    """
    Update the status of a job in the database. If job doesn't exist, it will create one.

    Args:
        job_id (str): Job ID
        status (str): Job status
    
    Returns:
        Job: Job object
    """
    with SessionLocal() as session:
        job = session.query(Job).filter(Job.id == job_id).first()
        if not job:
            job = Job(id=job_id, type='index_document', status="scheduled")
            session.add(job)
        job.status = status
        job.updated_at = datetime.datetime.utcnow()
        session.commit()
        session.refresh(job)
        return job

def get_job_status(job_id: str) -> Job:
    """
    Get the status of a job

    Args:
        job_id (str): Job ID
    
    Returns:
        Job: Job object
    """
    with SessionLocal() as session:
        job = session.query(Job).filter(Job.id == job_id).first()
        if job:
            return job.status
        else:
            return None
if __name__ == "__main__":
    init_db()

